# Testing conda on windows
name: conda - windows - test
on:
  push:
    branches:
      - workflow

jobs:
  test-conda-windows:
    name: Test conda Windows
    runs-on: "windows-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: myenv

      - name: install cmake and eigen
        shell: cmd /C CALL {0}
        run: |
            echo conda install cmake eigen
            conda list --name myenv
            echo dir eigen3.pc /S
            dir eigen3.pc
