# Testing conda on windows
name: conda - windows - test
on:
  push:
    branches:
      - workflow

jobs:
  test-conda-windows:
    name: Test conda Windows
    runs-on: "windows-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: myenv
      - name: install cmake and eigen
        shell: cmd /C CALL {0}
        steps:
          - run: echo conda install cmake eigen
          - run:      conda install cmake eigen
          - run: echo conda list --name myenv
          - run:      conda list --name myenv
          - run: echo dir eigen3.pc /S
          - run:      dir eigen3.pc
          - run: echo dir Eigen /S
          - run:      dir Eigen /S
          - run: echo CONDA_PREFIX=%CONDA_PREFIX
          - run: echo cd %CONDA_PREFIX%
          - run:      cd %CONDA_PREFIX%
          - run: echo dir eigen3.pc /S
          - run:      dir eigen3.pc
          - run: echo dir Eigen /S
          - run:      dir Eigen /S
