name: conda - windows - clang
on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        name: [windows-latest-clang-cl]

        include:
          - name: windows-latest-clang-cl
            os: windows-2019
            compiler: clang-cl

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule update --init
    - uses: goanpeca/setup-miniconda@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        activate-environment: myenv
        environment-file: .github/workflows/conda/conda-env.yml
        python-version: 3.7
    - name: Install cmake and eigen
      shell: cmd /C CALL {0}
      run: |
        conda install --yes cmake eigen
    - name: search for Eigen directory
      shell: cmd /C CALL {0}
      run: |
        echo cd = %cd%
        echo where cmake
             where cmake
        echo CONDA_PREFIX = %CONDA_PREFIX%
        echo dir %CONDA_PREFIX%
             dir %CONDA_PREFIX%
        echo cd %COMDA_PREFIX%
             cd %CONDA_PREFIX%
        echo dir
             dir
