name: conda - windows - test
on:
  push:
    branches:
      - master
      - 'stable/*'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: conda_env

    - name: Use conda to install eigen
      shell: cmd /C CALL {0}
      run: |
        echo conda install --yes eigen
             conda install --yes eigen

    - name: Check location of Eigen directory
      shell: cmd /C CALL {0}
      run: |
        echo dir %CONDA_PREFIX%\Library\include\Eigen
             dir %CONDA_PREFIX%\Library\include\Eigen

    - name: Build and test CppAD with Eigen
      shell: cmd /C CALL {0}
      run: |
        echo Use vcvarsall.bat to get proper verison of cmake
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        echo where camke
             where cmake
        echo mkdir build
             mkdir build
        echo cd build
             cd build
        echo set eigen_prefix=%CONDA_PREFIX%\Library
             set eigen_prefix=%CONDA_PREFIX%\Library
        echo Configure using eigen_prefix
        cmake ^
          -D CMAKE_BUILD_TYPE=release ^
          -G "NMake Makefiles" ^
          -D eigen_prefix=%eigen_prefix% ^
          ..
        REM Build and run tests.
        echo cmake --build . --target check
             cmake --build . --target check
